import type { DiffRadar, FlightEvent, Snapshot, Task, TraceSpan } from "./types";

const iso = (offsetMs: number) => new Date(Date.now() + offsetMs).toISOString();

const diff = (patch: Partial<DiffRadar>): DiffRadar => ({
  dirty: true,
  added: 0,
  modified: 0,
  deleted: 0,
  renamed: 0,
  untracked: 0,
  tests: 0,
  lockfiles: 0,
  generated_at: iso(-18_000),
  files: [],
  ...patch,
});

const flight = (project: string, status: string, offset = 20): FlightEvent[] => [
  { id: `${project}:brief`, at: iso(-(offset + 14) * 60_000), kind: "user", title: "mission brief", detail: project, source: "log" },
  { id: `${project}:tools`, at: iso(-(offset + 8) * 60_000), kind: "tool", title: "tool activity", detail: "inspection and edits", source: "trace" },
  { id: `${project}:status`, at: iso(-offset * 60_000), kind: "status", title: status, detail: "latest cockpit classification", status, source: "status" },
];

const turn = (id: string, summary: string, status: TraceSpan["status"], children: TraceSpan[], startMinutes: number, endMinutes = 1): TraceSpan => ({
  id,
  kind: "turn",
  name: "user turn",
  status,
  started_at: iso(-startMinutes * 60_000),
  ended_at: status === "running" ? undefined : iso(-endMinutes * 60_000),
  summary,
  children,
});

export const mockTasks = (): Task[] => [
  {
    id: "claude:788291c5-19ee-demo",
    session: {
      id: "788291c5-19ee-demo",
      agent: "claude",
      cwd: "/Users/hsy/work/kb-workspace/music-know-vault",
      title: "KnowVault prod rollout",
      last_event_at: iso(-2 * 60_000),
      events: [
        { at: iso(-19 * 60_000), type: "user", text: "check prod NCM config after pod restart" },
        { at: iso(-15 * 60_000), type: "tool", text: "grep rds and redis namespaces" },
        { at: iso(-9 * 60_000), type: "tool", text: "checked api-server and curation-server env" },
        { at: iso(-2 * 60_000), type: "assistant", text: "prod cluster may still miss one namespace. Should I prepare the opconfig checklist?" },
      ],
      trace: [
        turn("turn:prod", "verify prod rollout config", "succeeded", [
          {
            id: "tool:grep-prod",
            parent_id: "turn:prod",
            kind: "tool",
            name: "Bash",
            status: "succeeded",
            started_at: iso(-15 * 60_000),
            ended_at: iso(-14.5 * 60_000),
            detail: 'grep -rn "rds\\|redis\\|kafka" knowvault-*/src/main/resources',
            summary: "found service namespace mismatch",
          },
          {
            id: "tool:read-opconfig",
            parent_id: "turn:prod",
            kind: "tool",
            name: "Read",
            status: "succeeded",
            started_at: iso(-11 * 60_000),
            ended_at: iso(-10.5 * 60_000),
            detail: "opconfig/prod/music-know-vault.yaml",
          },
          {
            id: "assistant:prod",
            parent_id: "turn:prod",
            kind: "assistant",
            name: "assistant",
            status: "succeeded",
            started_at: iso(-2 * 60_000),
            ended_at: iso(-2 * 60_000),
            summary: "asking whether to prepare the checklist",
          },
        ], 19, 2),
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 0,
        pane_id: 0,
        workspace: "main",
        tab_title: "music",
        cwd: "/Users/hsy/work/kb-workspace/music-know-vault",
        tty_name: "ttys000",
      },
      confidence: 195,
      reasons: ["pid tty match", "cwd related", "agent process on pane tty"],
    },
    status: "needs_attention",
    status_explanation: {
      status: "needs_attention",
      rule: "assistant_question",
      reason: "agent is asking for a decision",
      latest_assistant_at: iso(-2 * 60_000),
      last_event_at: iso(-2 * 60_000),
      evidence: ["assistant asked whether to prepare prod checklist"],
    },
    attention_reason: "agent is asking for a decision",
    summary: "prod config check found a namespace mismatch; agent wants confirmation before writing the checklist",
    diff: diff({
      repo_root: "/Users/hsy/work/kb-workspace/music-know-vault",
      branch: "release-web",
      added: 1,
      modified: 4,
      tests: 2,
      summary: "1 added, 4 modified, prod config notes",
      files: [
        { path: "knowvault-api-server/src/main/resources/application-prod.yml", status: "modified", additions: 12, deletions: 4 },
        { path: "knowvault-curation-server/src/main/resources/application-prod.yml", status: "modified", additions: 8, deletions: 2 },
        { path: "docs/prod-rollout-checklist.md", status: "added", additions: 64 },
        { path: "scripts/check-prod-config.sh", status: "modified", additions: 33, deletions: 7 },
      ],
    }),
    flight: flight("knowvault-prod", "needs_attention", 2),
  },
  {
    id: "codex:019ee3a9-release-demo",
    session: {
      id: "019ee3a9-release-demo",
      agent: "codex",
      cwd: "/Users/hsy/dev/release-web",
      title: "Release web verification",
      last_event_at: iso(-18_000),
      events: [
        { at: iso(-28 * 60_000), type: "user", text: "verify release-web build and auth redirect" },
        { at: iso(-18 * 60_000), type: "tool", text: "ran pnpm test --filter auth" },
        { at: iso(-4 * 60_000), type: "tool", text: "running pnpm build" },
        { at: iso(-18_000), type: "system", text: "tool still running" },
      ],
      trace: [
        turn("turn:release", "release-web validation", "running", [
          {
            id: "tool:auth-tests",
            parent_id: "turn:release",
            kind: "tool",
            name: "exec_command",
            status: "succeeded",
            started_at: iso(-18 * 60_000),
            ended_at: iso(-15 * 60_000),
            detail: "pnpm test --filter auth",
            summary: "auth tests passed",
          },
          {
            id: "subagent:visual",
            parent_id: "turn:release",
            kind: "subagent",
            name: "spawn_agent",
            status: "running",
            started_at: iso(-11 * 60_000),
            detail: "visual regression sidecar",
            summary: "checking login and release pages",
          },
          {
            id: "tool:build",
            parent_id: "turn:release",
            kind: "tool",
            name: "exec_command",
            status: "running",
            started_at: iso(-4 * 60_000),
            detail: "pnpm build",
            summary: "production build in progress",
          },
        ], 28),
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 4,
        pane_id: 9,
        workspace: "main",
        tab_title: "release-web",
        cwd: "/Users/hsy/dev/release-web",
        tty_name: "ttys009",
      },
      confidence: 98,
      reasons: ["pid tty match", "cwd match"],
    },
    status: "working",
    status_explanation: {
      status: "working",
      rule: "trace_active",
      reason: "blocking build trace is still running",
      active_trace: { id: "tool:build", kind: "tool", name: "exec_command", started_at: iso(-4 * 60_000), detail: "pnpm build" },
      background_run_traces: [{ id: "subagent:visual", kind: "subagent", name: "spawn_agent", started_at: iso(-11 * 60_000), summary: "visual regression sidecar" }],
      evidence: ["tool exec_command is running", "subagent visual regression is running"],
    },
    summary: "release-web tests passed; production build and visual sidecar are still running",
    diff: diff({
      repo_root: "/Users/hsy/dev/release-web",
      branch: "release/2026-04-30",
      modified: 8,
      renamed: 1,
      tests: 3,
      lockfiles: 1,
      summary: "8 modified, 1 renamed, lockfile touched",
      files: [
        { path: "src/routes/auth/callback.ts", status: "modified", additions: 36, deletions: 9 },
        { path: "src/routes/release/index.tsx", status: "modified", additions: 22, deletions: 5 },
        { path: "src/routes/release/release.spec.ts", status: "modified", additions: 40, deletions: 0 },
        { path: "package-lock.json", status: "modified", additions: 120, deletions: 118 },
        { path: "src/components/StatusBanner.tsx", status: "renamed", additions: 8, deletions: 3 },
      ],
    }),
    flight: flight("release-web", "working", 1),
  },
  {
    id: "claude:pay-auth-blocked-demo",
    session: {
      id: "pay-auth-blocked-demo",
      agent: "claude",
      cwd: "/Users/hsy/dev/payments-api",
      title: "Payment API auth refresh",
      last_event_at: iso(-7 * 60_000),
      events: [
        { at: iso(-31 * 60_000), type: "user", text: "refresh payment webhook auth flow" },
        { at: iso(-14 * 60_000), type: "tool", text: "ran go test ./internal/webhook" },
        { at: iso(-9 * 60_000), type: "error", text: "401 unauthorized from sandbox token endpoint" },
        { at: iso(-7 * 60_000), type: "assistant", text: "blocked on sandbox credentials" },
      ],
      trace: [
        turn("turn:pay", "refresh webhook auth", "failed", [
          {
            id: "tool:pay-test",
            parent_id: "turn:pay",
            kind: "tool",
            name: "exec_command",
            status: "failed",
            started_at: iso(-14 * 60_000),
            ended_at: iso(-9 * 60_000),
            exit_code: 1,
            detail: "go test ./internal/webhook",
            summary: "401 unauthorized from sandbox token endpoint",
          },
        ], 31, 7),
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 5,
        pane_id: 11,
        workspace: "main",
        tab_title: "payments",
        cwd: "/Users/hsy/dev/payments-api",
        tty_name: "ttys011",
      },
      confidence: 91,
      reasons: ["cwd match", "agent process on pane tty"],
    },
    status: "blocked",
    status_explanation: {
      status: "blocked",
      rule: "attention_pattern",
      rule_severity: "blocked",
      reason: "authentication required",
      why_not_working: "latest blocking event requires human credential input",
      evidence: ["401 unauthorized", "sandbox token endpoint rejected request"],
    },
    attention_reason: "sandbox credentials are missing",
    summary: "webhook auth refresh is blocked until sandbox credentials are refreshed",
    diff: diff({
      repo_root: "/Users/hsy/dev/payments-api",
      branch: "agent/webhook-auth",
      added: 1,
      modified: 5,
      tests: 2,
      summary: "auth client and webhook tests changed",
      files: [
        { path: "internal/auth/client.go", status: "modified", additions: 58, deletions: 24 },
        { path: "internal/webhook/handler.go", status: "modified", additions: 28, deletions: 6 },
        { path: "internal/webhook/handler_test.go", status: "modified", additions: 77, deletions: 18 },
        { path: "docs/sandbox-token-rotation.md", status: "added", additions: 38 },
      ],
    }),
    flight: flight("payments-api", "blocked", 7),
  },
  {
    id: "codex:019ddc4c-cockpit-demo",
    session: {
      id: "019ddc4c-cockpit-demo",
      agent: "codex",
      cwd: "/Users/hsy/dev/cockpit",
      title: "Cockpit LAN dashboard",
      last_event_at: iso(-3 * 60_000),
      events: [
        { at: iso(-50 * 60_000), type: "user", text: "build readonly LAN dashboard" },
        { at: iso(-28 * 60_000), type: "tool", text: "added share server and readonly API" },
        { at: iso(-12 * 60_000), type: "tool", text: "ran go test ./... and wails build" },
        { at: iso(-3 * 60_000), type: "assistant", text: "LAN dashboard is ready and packaged" },
      ],
      trace: [
        turn("turn:cockpit", "build readonly LAN cockpit", "succeeded", [
          {
            id: "tool:server",
            parent_id: "turn:cockpit",
            kind: "tool",
            name: "apply_patch",
            status: "succeeded",
            started_at: iso(-28 * 60_000),
            ended_at: iso(-22 * 60_000),
            summary: "added share_server.go",
          },
          {
            id: "tool:verify",
            parent_id: "turn:cockpit",
            kind: "tool",
            name: "exec_command",
            status: "succeeded",
            started_at: iso(-12 * 60_000),
            ended_at: iso(-8 * 60_000),
            detail: "go test ./... && wails build",
          },
        ], 50, 3),
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 1,
        pane_id: 2,
        workspace: "main",
        tab_title: "cockpit",
        cwd: "/Users/hsy/dev/cockpit",
        tty_name: "ttys002",
      },
      confidence: 999,
      reasons: ["manual attach"],
    },
    status: "idle",
    status_explanation: {
      status: "idle",
      rule: "idle_timeout",
      reason: "agent response ended; idle for 3m",
      latest_assistant_at: iso(-3 * 60_000),
      last_event_at: iso(-3 * 60_000),
      evidence: ["assistant response is older than settle window"],
    },
    summary: "readonly LAN dashboard is implemented, packaged, and ready for review",
    diff: diff({
      repo_root: "/Users/hsy/dev/cockpit",
      branch: "main",
      added: 2,
      modified: 9,
      tests: 3,
      summary: "2 added, 9 modified, readonly web share",
      files: [
        { path: "share_server.go", status: "added", additions: 265 },
        { path: "share_server_test.go", status: "added", additions: 43 },
        { path: "frontend/src/App.tsx", status: "modified", additions: 281, deletions: 38 },
        { path: "frontend/src/style.css", status: "modified", additions: 252, deletions: 1 },
        { path: "frontend/src/api.ts", status: "modified", additions: 124, deletions: 8 },
      ],
    }),
    debrief: {
      task_id: "codex:019ddc4c-cockpit-demo",
      session_id: "019ddc4c-cockpit-demo",
      generated_at: iso(-2 * 60_000),
      input_hash: "mock-lan",
      text: "## Completed\nReadonly LAN dashboard, owner welcome modal, and cockpit scrollbars are wired.\n\n## Current State\nThe desktop app starts a separate readonly server with snapshot and settings endpoints.\n\n## Changed Files\nGo share server, frontend runtime detection, readonly controls, README, and product notes.\n\n## Tests\n`npm run build`, `go test ./...`, and `wails build` passed.\n\n## Risks\nRemote viewers still need network access to the host machine.\n\n## Next Action\nReview the LAN page from another device.",
    },
    flight: flight("cockpit-lan", "idle", 3),
  },
  {
    id: "claude:taxonomy-wait-demo",
    session: {
      id: "taxonomy-wait-demo",
      agent: "claude",
      cwd: "/Users/hsy/work/content-console",
      title: "Content taxonomy cleanup",
      last_event_at: iso(-6 * 60_000),
      events: [
        { at: iso(-24 * 60_000), type: "tool", text: "scanned duplicate topic mappings" },
        { at: iso(-10 * 60_000), type: "tool", text: "generated taxonomy migration plan" },
        { at: iso(-6 * 60_000), type: "assistant", text: "waiting for confirmation on merging evergreen and classic tags" },
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 6,
        pane_id: 13,
        workspace: "main",
        tab_title: "content",
        cwd: "/Users/hsy/work/content-console",
        tty_name: "ttys013",
      },
      confidence: 86,
      reasons: ["cwd match", "tty related"],
    },
    status: "waiting",
    status_explanation: {
      status: "waiting",
      rule: "assistant_question",
      reason: "assistant is waiting for a product decision",
      latest_assistant_at: iso(-6 * 60_000),
      evidence: ["merge evergreen and classic tags?"],
    },
    attention_reason: "taxonomy merge needs product confirmation",
    summary: "taxonomy cleanup is staged; agent is waiting on merge direction",
    diff: diff({
      repo_root: "/Users/hsy/work/content-console",
      branch: "taxonomy-cleanup",
      modified: 2,
      untracked: 2,
      summary: "topic mappings and migration notes",
      files: [
        { path: "data/topic-map.json", status: "modified", additions: 204, deletions: 71 },
        { path: "migrations/20260430_merge_topics.sql", status: "untracked", additions: 88 },
      ],
    }),
    flight: flight("taxonomy", "waiting", 6),
  },
  {
    id: "claude:flyway-done-demo",
    session: {
      id: "flyway-done-demo",
      agent: "claude",
      cwd: "/Users/hsy/work/kb-workspace/music-know-vault",
      title: "Flyway startup check",
      last_event_at: iso(-19 * 60_000),
      events: [
        { at: iso(-42 * 60_000), type: "tool", text: "read curation server pom.xml" },
        { at: iso(-26 * 60_000), type: "tool", text: "ran mvn test for Flyway startup" },
        { at: iso(-19 * 60_000), type: "assistant", text: "confirmed c3p0 exclusion keeps Boot 3 datasource detection clean" },
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 0,
        pane_id: 0,
        workspace: "main",
        tab_title: "music",
        cwd: "/Users/hsy/work/kb-workspace/music-know-vault",
        tty_name: "ttys000",
      },
      confidence: 88,
      reasons: ["pid tty match", "cwd related"],
    },
    status: "completed",
    summary: "Flyway startup behavior is confirmed after excluding the legacy c3p0 dependency",
    diff: diff({
      repo_root: "/Users/hsy/work/kb-workspace/music-know-vault",
      branch: "fix/flyway-startup",
      modified: 3,
      tests: 1,
      summary: "pom cleanup and startup test notes",
      files: [
        { path: "knowvault-curation-server/pom.xml", status: "modified", additions: 9, deletions: 16 },
        { path: "docs/flyway-startup-check.md", status: "modified", additions: 34, deletions: 2 },
      ],
    }),
    flight: flight("flyway", "completed", 19),
  },
  {
    id: "codex:deploy-drift-demo",
    session: {
      id: "deploy-drift-demo",
      agent: "codex",
      cwd: "/Users/hsy/work/kb-workspace/deploy",
      title: "Deployment notes",
      last_event_at: iso(-38 * 60_000),
      events: [
        { at: iso(-63 * 60_000), type: "user", text: "check deployment notes and terraform drift" },
        { at: iso(-51 * 60_000), type: "tool", text: "terraform plan is still streaming" },
        { at: iso(-38 * 60_000), type: "system", text: "no new output since" },
      ],
      trace: [
        turn("turn:deploy", "check terraform drift", "running", [
          {
            id: "tool:terraform",
            parent_id: "turn:deploy",
            kind: "tool",
            name: "exec_command",
            status: "running",
            started_at: iso(-51 * 60_000),
            detail: "terraform plan -refresh-only",
            summary: "long-running terraform plan",
          },
        ], 63),
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 2,
        pane_id: 4,
        workspace: "main",
        tab_title: "deploy",
        cwd: "/Users/hsy/work/kb-workspace/deploy",
        tty_name: "ttys004",
      },
      confidence: 76,
      reasons: ["cwd match", "agent process on pane tty"],
    },
    status: "drift",
    status_explanation: {
      status: "drift",
      rule: "long_running_trace",
      rule_severity: "drift",
      reason: "terraform plan has been running for 51m",
      why_not_idle: "a tool trace is still running",
      evidence: ["long running trace: exec_command terraform plan"],
    },
    attention_reason: "terraform plan has been running for 51m",
    summary: "deployment drift check is running longer than expected",
    diff: diff({
      repo_root: "/Users/hsy/work/kb-workspace/deploy",
      branch: "infra/drift-scan",
      modified: 1,
      summary: "deployment notes updated",
      files: [{ path: "notes/prod-drift-2026-04-30.md", status: "modified", additions: 18, deletions: 3 }],
    }),
    flight: flight("deploy", "drift", 38),
  },
  {
    id: "codex:my-buddies-unbound-demo",
    session: {
      id: "my-buddies-unbound-demo",
      agent: "codex",
      cwd: "/Users/hsy/dev/my-buddies",
      title: "Buddy room polish",
      last_event_at: iso(-49 * 60_000),
      events: [
        { at: iso(-55 * 60_000), type: "system", text: "session found in Codex logs" },
        { at: iso(-49 * 60_000), type: "system", text: "no reliable pane match" },
      ],
    },
    binding: { confidence: 0, reasons: ["no pane with matching tty or cwd"] },
    status: "unbound",
    summary: "room polish session exists in logs, but Cockpit cannot bind it to a visible WezTerm pane",
    diff: diff({
      repo_root: "/Users/hsy/dev/my-buddies",
      branch: "room-polish",
      modified: 5,
      untracked: 3,
      summary: "voxel room and mood labels changed",
      files: [
        { path: "src/room/AgentRoom.tsx", status: "modified", additions: 92, deletions: 41 },
        { path: "src/room/materials.ts", status: "modified", additions: 34, deletions: 10 },
        { path: "assets/mock-agents.json", status: "untracked", additions: 55 },
      ],
    }),
    flight: flight("my-buddies", "unbound", 49),
  },
];

export const mockSnapshot = (): Snapshot => ({
  built_at: new Date().toISOString(),
  tasks: mockTasks(),
  panes: [
    { window_id: 1, tab_id: 0, pane_id: 0, workspace: "main", tab_title: "music", cwd: "/Users/hsy/work/kb-workspace/music-know-vault", tty_name: "ttys000" },
    { window_id: 1, tab_id: 1, pane_id: 2, workspace: "main", tab_title: "cockpit", cwd: "/Users/hsy/dev/cockpit", tty_name: "ttys002", is_active: true },
    { window_id: 1, tab_id: 2, pane_id: 4, workspace: "main", tab_title: "deploy", cwd: "/Users/hsy/work/kb-workspace/deploy", tty_name: "ttys004" },
    { window_id: 1, tab_id: 4, pane_id: 9, workspace: "main", tab_title: "release-web", cwd: "/Users/hsy/dev/release-web", tty_name: "ttys009" },
    { window_id: 1, tab_id: 5, pane_id: 11, workspace: "main", tab_title: "payments", cwd: "/Users/hsy/dev/payments-api", tty_name: "ttys011" },
    { window_id: 1, tab_id: 6, pane_id: 13, workspace: "main", tab_title: "content", cwd: "/Users/hsy/work/content-console", tty_name: "ttys013" },
  ],
  processes: [
    { pid: 42380, ppid: 42001, tty: "ttys000", args: "claude --dangerously-skip-permissions" },
    { pid: 43122, ppid: 42001, tty: "ttys009", args: "codex exec" },
    { pid: 43902, ppid: 42001, tty: "ttys011", args: "claude" },
  ],
  missions: [
    {
      id: "repo:/Users/hsy/work/kb-workspace/music-know-vault",
      name: "music-know-vault",
      repo_root: "/Users/hsy/work/kb-workspace/music-know-vault",
      status: "needs_attention",
      task_ids: ["claude:788291c5-19ee-demo", "claude:flyway-done-demo"],
      attention: 1,
      working: 0,
      drift: 0,
      blocked: 0,
      idle: 0,
      completed: 1,
      changed_files: 6,
      last_event_at: iso(-2 * 60_000),
      summary: "prod config needs a decision; Flyway check is complete",
    },
    {
      id: "repo:/Users/hsy/dev/release-web",
      name: "release-web",
      repo_root: "/Users/hsy/dev/release-web",
      status: "working",
      task_ids: ["codex:019ee3a9-release-demo"],
      attention: 0,
      working: 1,
      drift: 0,
      blocked: 0,
      idle: 0,
      completed: 0,
      changed_files: 9,
      last_event_at: iso(-18_000),
      summary: "build and visual sidecar still running",
    },
    {
      id: "repo:/Users/hsy/dev/payments-api",
      name: "payments-api",
      repo_root: "/Users/hsy/dev/payments-api",
      status: "blocked",
      task_ids: ["claude:pay-auth-blocked-demo"],
      attention: 0,
      working: 0,
      drift: 0,
      blocked: 1,
      idle: 0,
      completed: 0,
      changed_files: 4,
      last_event_at: iso(-7 * 60_000),
      summary: "sandbox credentials are required",
    },
    {
      id: "repo:/Users/hsy/dev/cockpit",
      name: "cockpit",
      repo_root: "/Users/hsy/dev/cockpit",
      status: "idle",
      task_ids: ["codex:019ddc4c-cockpit-demo"],
      attention: 0,
      working: 0,
      drift: 0,
      blocked: 0,
      idle: 1,
      completed: 0,
      changed_files: 11,
      last_event_at: iso(-3 * 60_000),
      summary: "readonly LAN dashboard is ready for review",
    },
    {
      id: "repo:/Users/hsy/work/kb-workspace/deploy",
      name: "kb-deploy",
      repo_root: "/Users/hsy/work/kb-workspace/deploy",
      status: "drift",
      task_ids: ["codex:deploy-drift-demo"],
      attention: 0,
      working: 0,
      drift: 1,
      blocked: 0,
      idle: 0,
      completed: 0,
      changed_files: 1,
      last_event_at: iso(-38 * 60_000),
      summary: "terraform plan is running long",
    },
  ],
  done_inbox: [
    {
      id: "done:cockpit-lan",
      task_id: "codex:019ddc4c-cockpit-demo",
      session_id: "019ddc4c-cockpit-demo",
      agent: "codex",
      project: "cockpit",
      title: "Readonly LAN dashboard",
      status: "completed",
      completed_at: iso(-3 * 60_000),
      reviewed: false,
      pane_id: 2,
      summary: "LAN readonly dashboard, welcome modal, and cockpit scrollbars are implemented",
      diff: diff({ repo_root: "/Users/hsy/dev/cockpit", branch: "main", added: 2, modified: 9, tests: 3, summary: "2 added, 9 modified" }),
    },
    {
      id: "done:flyway",
      task_id: "claude:flyway-done-demo",
      session_id: "flyway-done-demo",
      agent: "claude",
      project: "music-know-vault",
      title: "Flyway startup check",
      status: "completed",
      completed_at: iso(-19 * 60_000),
      reviewed: false,
      pane_id: 0,
      summary: "Flyway startup behavior is confirmed after excluding legacy c3p0",
      diff: diff({ repo_root: "/Users/hsy/work/kb-workspace/music-know-vault", branch: "fix/flyway-startup", modified: 3, tests: 1, summary: "3 modified" }),
    },
    {
      id: "done:content-taxonomy",
      task_id: "claude:taxonomy-wait-demo",
      session_id: "taxonomy-wait-demo",
      agent: "claude",
      project: "content-console",
      title: "Taxonomy cleanup plan",
      status: "waiting",
      completed_at: iso(-34 * 60_000),
      reviewed: true,
      pane_id: 13,
      summary: "taxonomy migration plan is drafted and waiting for product confirmation",
      diff: diff({ repo_root: "/Users/hsy/work/content-console", branch: "taxonomy-cleanup", modified: 2, untracked: 2, summary: "2 modified, 2 untracked" }),
    },
  ],
  errors: [],
});
