import type { Snapshot, Task } from "./types";

const iso = (offsetMs: number) => new Date(Date.now() + offsetMs).toISOString();

export const mockTasks = (): Task[] => [
  {
    id: "codex:019de0b2-71d0-demo",
    session: {
      id: "019de0b2-71d0-demo",
      agent: "codex",
      cwd: "/Users/hsy/dev/frontend",
      title: "Route guard refactor",
      last_event_at: iso(-2 * 60_000),
      events: [
        { at: iso(-7 * 60_000), type: "tool", text: "edited src/router/guards.ts" },
        { at: iso(-6 * 60_000), type: "tool", text: "ran pnpm test router.guard.spec.ts" },
        { at: iso(-5 * 60_000), type: "result", text: "1 failed, 12 passed" },
        { at: iso(-2 * 60_000), type: "assistant", text: "asking whether to preserve legacy redirect behavior" },
      ],
      trace: [
        {
          id: "turn:1",
          kind: "turn",
          name: "user turn",
          status: "succeeded",
          started_at: iso(-7 * 60_000),
          ended_at: iso(-2 * 60_000),
          summary: "refactor route guard behavior",
          children: [
            {
              id: "call:edit",
              parent_id: "turn:1",
              kind: "tool",
              name: "apply_patch",
              status: "succeeded",
              started_at: iso(-7 * 60_000),
              ended_at: iso(-6.5 * 60_000),
              summary: "edited src/router/guards.ts",
            },
            {
              id: "call:test",
              parent_id: "turn:1",
              kind: "tool",
              name: "exec_command",
              status: "failed",
              started_at: iso(-6 * 60_000),
              ended_at: iso(-5 * 60_000),
              exit_code: 1,
              detail: "pnpm test router.guard.spec.ts",
              summary: "1 failed, 12 passed",
            },
            {
              id: "assistant:1",
              parent_id: "turn:1",
              kind: "assistant",
              name: "assistant",
              status: "succeeded",
              started_at: iso(-2 * 60_000),
              ended_at: iso(-2 * 60_000),
              summary: "asking whether to preserve legacy redirect behavior",
            },
          ],
        },
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 3,
        pane_id: 7,
        workspace: "main",
        tab_title: "frontend",
        cwd: "/Users/hsy/dev/frontend",
        tty_name: "ttys007",
      },
      confidence: 94,
      reasons: ["pid tty match", "cwd match"],
    },
    status: "needs_attention",
    attention_reason: "tests failed; agent is waiting for a decision",
    summary: "tests failed after changing route guards; agent is waiting for direction",
    diff: {
      repo_root: "/Users/hsy/dev/frontend",
      branch: "agent/route-guard",
      dirty: true,
      added: 0,
      modified: 3,
      deleted: 0,
      renamed: 0,
      untracked: 1,
      tests: 2,
      lockfiles: 0,
      summary: "3 modified, 1 untracked",
      generated_at: iso(-20_000),
      files: [
        { path: "src/router/guards.ts", status: "modified", additions: 42, deletions: 18 },
        { path: "src/router/guards.spec.ts", status: "modified", additions: 11, deletions: 2 },
        { path: "test/fixtures/legacy-redirect.json", status: "untracked" },
      ],
    },
    flight: [
      { id: "f1", at: iso(-7 * 60_000), kind: "user", title: "user prompt", detail: "refactor route guard behavior", source: "log" },
      { id: "f2", at: iso(-6 * 60_000), kind: "tool", title: "pnpm test", detail: "router.guard.spec.ts", status: "failed", source: "trace" },
      { id: "f3", at: iso(-2 * 60_000), kind: "status", title: "needs_attention", detail: "tests failed; decision needed", status: "needs_attention", source: "status" },
    ],
  },
  {
    id: "codex:019ddc4c-620e-demo",
    session: {
      id: "019ddc4c-620e-demo",
      agent: "codex",
      cwd: "/Users/hsy/dev/cockpit",
      title: "Cockpit desktop shell",
      last_event_at: iso(-2 * 60_000),
      events: [
        { at: iso(-4 * 60_000), type: "user", text: "use mock data to restore the cockpit TUI style" },
        { at: iso(-3 * 60_000), type: "tool", text: "patched internal/tui/model.go" },
        { at: iso(-2 * 60_000), type: "assistant", text: "desktop shell is updated and waiting for the next instruction" },
      ],
      trace: [
        {
          id: "turn:1",
          kind: "turn",
          name: "user turn",
          status: "succeeded",
          started_at: iso(-4 * 60_000),
          ended_at: iso(-2 * 60_000),
          summary: "build cockpit desktop app",
          children: [
            {
              id: "call:inspect",
              parent_id: "turn:1",
              kind: "tool",
              name: "exec_command",
              status: "succeeded",
              started_at: iso(-3 * 60_000),
              ended_at: iso(-140_000),
              detail: "rg --files",
            },
            {
              id: "subagent:ui",
              parent_id: "turn:1",
              kind: "subagent",
              name: "spawn_agent",
              status: "succeeded",
              started_at: iso(-90_000),
              ended_at: iso(-70_000),
              detail: "frontend polish worker",
            },
            {
              id: "call:build",
              parent_id: "turn:1",
              kind: "tool",
              name: "exec_command",
              status: "succeeded",
              started_at: iso(-70_000),
              ended_at: iso(-65_000),
              detail: "wails build",
            },
            {
              id: "assistant:1",
              parent_id: "turn:1",
              kind: "assistant",
              name: "assistant",
              status: "succeeded",
              started_at: iso(-2 * 60_000),
              ended_at: iso(-2 * 60_000),
              summary: "desktop shell is updated and waiting for the next instruction",
            },
          ],
        },
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 1,
        pane_id: 2,
        workspace: "main",
        tab_title: "cockpit",
        cwd: "/Users/hsy/dev/cockpit",
        tty_name: "ttys002",
      },
      confidence: 999,
      reasons: ["manual attach"],
    },
    status: "idle",
    status_explanation: {
      status: "idle",
      rule: "idle_timeout",
      reason: "agent response ended; idle for 2m0s",
      latest_assistant_at: iso(-2 * 60_000),
      last_event_at: iso(-2 * 60_000),
      evidence: ["assistant response is older than settle window"],
    },
    summary: "desktop shell is updated and waiting for the next instruction",
    diff: {
      repo_root: "/Users/hsy/dev/cockpit",
      branch: "main",
      dirty: true,
      added: 2,
      modified: 6,
      deleted: 0,
      renamed: 0,
      untracked: 0,
      tests: 1,
      lockfiles: 0,
      summary: "2 added, 6 modified",
      generated_at: iso(-15_000),
      files: [
        { path: "internal/gitradar/gitradar.go", status: "added", additions: 210 },
        { path: "frontend/src/App.tsx", status: "modified", additions: 180, deletions: 12 },
      ],
    },
    debrief: {
      task_id: "codex:019ddc4c-620e-demo",
      session_id: "019ddc4c-620e-demo",
      generated_at: iso(-60_000),
      input_hash: "mock",
      text: "## Completed\nDesktop shell and status panels are wired.\n\n## Current State\nIdle and ready for review.\n\n## Changed Files\nFrontend and Go snapshot code changed.\n\n## Tests\nMock build passed in browser mode.\n\n## Risks\nNative Wails bindings are not active in browser mode.\n\n## Next Action\nReview the generated panels.",
    },
  },
  {
    id: "claude:788291c5-19ee-demo",
    session: {
      id: "788291c5-19ee-demo",
      agent: "claude",
      cwd: "/Users/hsy/work/kb-workspace/music-know-vault",
      title: "Flyway startup check",
      last_event_at: iso(-3 * 60_000),
      events: [
        { at: iso(-9 * 60_000), type: "tool", text: "read curation server pom.xml" },
        { at: iso(-4 * 60_000), type: "tool", text: "ran mvn test for Flyway startup" },
        { at: iso(-3 * 60_000), type: "assistant", text: "confirmed c3p0 exclusion keeps Boot 3 datasource detection clean" },
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 0,
        pane_id: 0,
        workspace: "main",
        tab_title: "music",
        cwd: "/Users/hsy/work/kb-workspace",
        tty_name: "ttys000",
      },
      confidence: 88,
      reasons: ["pid tty match", "cwd related", "agent process on pane tty"],
    },
    status: "idle",
    status_explanation: {
      status: "idle",
      rule: "idle_timeout",
      reason: "agent response ended; idle for 3m0s",
      latest_assistant_at: iso(-3 * 60_000),
      last_event_at: iso(-3 * 60_000),
      evidence: ["assistant response is older than settle window"],
    },
    summary: "confirmed Flyway startup behavior after excluding a legacy c3p0 dependency",
  },
  {
    id: "claude:57665bc0-123e-demo",
    session: {
      id: "57665bc0-123e-demo",
      agent: "claude",
      cwd: "/Users/hsy/work/kb-workspace",
      title: "Deployment notes",
      last_event_at: iso(-14 * 60_000),
      events: [
        { at: iso(-21 * 60_000), type: "user", text: "check deployment notes" },
        { at: iso(-18 * 60_000), type: "tool", text: "read deployment README" },
        { at: iso(-14 * 60_000), type: "system", text: "no new output since" },
      ],
    },
    binding: {
      pane: {
        window_id: 1,
        tab_id: 2,
        pane_id: 4,
        workspace: "main",
        tab_title: "deploy",
        cwd: "/Users/hsy/work/kb-workspace",
        tty_name: "ttys004",
      },
      confidence: 71,
      reasons: ["cwd match", "agent process on pane tty"],
    },
    status: "drift",
    status_explanation: {
      status: "drift",
      rule: "long_running_trace",
      rule_severity: "drift",
      reason: "exec_command has been running for 22m",
      why_not_idle: "a tool or subagent is still running",
      evidence: ["long running trace: tool exec_command"],
    },
    attention_reason: "exec_command has been running for 22m",
    summary: "deployment note check is still running longer than expected",
  },
  {
    id: "codex:019dd2e0-6a8c-demo",
    session: {
      id: "019dd2e0-6a8c-demo",
      agent: "codex",
      cwd: "/Users/hsy/dev/my-buddies",
      title: "Unbound session",
      last_event_at: iso(-42 * 60_000),
      events: [
        { at: iso(-46 * 60_000), type: "system", text: "session found in Codex logs" },
        { at: iso(-42 * 60_000), type: "system", text: "no reliable pane match" },
      ],
    },
    binding: { confidence: 0 },
    status: "unbound",
    summary: "session found in logs, but no reliable pane match",
  },
];

export const mockSnapshot = (): Snapshot => ({
  built_at: new Date().toISOString(),
  tasks: mockTasks(),
  panes: [
    { window_id: 1, tab_id: 3, pane_id: 7, workspace: "main", tab_title: "frontend", cwd: "/Users/hsy/dev/frontend", tty_name: "ttys007" },
    { window_id: 1, tab_id: 1, pane_id: 2, workspace: "main", tab_title: "cockpit", cwd: "/Users/hsy/dev/cockpit", tty_name: "ttys002", is_active: true },
    { window_id: 1, tab_id: 0, pane_id: 0, workspace: "main", tab_title: "music", cwd: "/Users/hsy/work/kb-workspace", tty_name: "ttys000" },
    { window_id: 1, tab_id: 2, pane_id: 4, workspace: "main", tab_title: "deploy", cwd: "/Users/hsy/work/kb-workspace", tty_name: "ttys004" },
  ],
  processes: [],
  missions: [
    {
      id: "repo:/Users/hsy/dev/cockpit",
      name: "cockpit",
      repo_root: "/Users/hsy/dev/cockpit",
      status: "idle",
      task_ids: ["codex:019ddc4c-620e-demo"],
      attention: 0,
      working: 0,
      drift: 0,
      blocked: 0,
      idle: 1,
      completed: 0,
      changed_files: 2,
      last_event_at: iso(-2 * 60_000),
      summary: "desktop shell is updated and waiting for the next instruction",
    },
    {
      id: "repo:/Users/hsy/dev/frontend",
      name: "frontend",
      repo_root: "/Users/hsy/dev/frontend",
      status: "needs_attention",
      task_ids: ["codex:019de0b2-71d0-demo"],
      attention: 1,
      working: 0,
      drift: 0,
      blocked: 0,
      idle: 0,
      completed: 0,
      changed_files: 3,
      last_event_at: iso(-2 * 60_000),
      summary: "tests failed after changing route guards",
    },
  ],
  done_inbox: [
    {
      id: "codex_019done-demo",
      task_id: "codex:019ddc4c-620e-demo",
      session_id: "019ddc4c-620e-demo",
      agent: "codex",
      project: "cockpit",
      title: "Cockpit desktop shell",
      status: "completed",
      completed_at: iso(-9 * 60_000),
      reviewed: false,
      summary: "desktop shell is updated and waiting for review",
      diff: {
        repo_root: "/Users/hsy/dev/cockpit",
        branch: "main",
        dirty: true,
        added: 2,
        modified: 6,
        deleted: 0,
        renamed: 0,
        untracked: 0,
        tests: 1,
        lockfiles: 0,
        summary: "2 added, 6 modified",
      },
    },
  ],
  errors: [],
});
