// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';
import {main} from '../models';

export function ArchiveDoneItem(arg1:string):Promise<app.Snapshot>;

export function ArchiveTask(arg1:string):Promise<app.Snapshot>;

export function AttachTask(arg1:string,arg2:number):Promise<app.Snapshot>;

export function DetachTask(arg1:string):Promise<app.Snapshot>;

export function GenerateDebrief(arg1:string):Promise<app.Task>;

export function GetDemoSnapshot():Promise<app.Snapshot>;

export function GetLogPath():Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function GetShareServer():Promise<main.ShareServerInfo>;

export function GetSnapshot():Promise<app.Snapshot>;

export function IgnoreTask(arg1:string):Promise<app.Snapshot>;

export function OpenPane(arg1:number):Promise<void>;

export function RefreshSummary(arg1:string):Promise<app.Task>;

export function RenameMission(arg1:string,arg2:string):Promise<app.Snapshot>;

export function ReportFrontendError(arg1:string,arg2:string):Promise<void>;

export function RestoreTask(arg1:string):Promise<app.Snapshot>;

export function ReviewDoneItem(arg1:string):Promise<app.Snapshot>;

export function SaveSettings(arg1:config.Settings):Promise<config.Settings>;

export function SearchPrompts(arg1:string):Promise<Array<app.PromptSearchResult>>;

export function StartReadonlyServer():Promise<main.ShareServerInfo>;
