// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveDoneItem(arg1) {
  return window['go']['main']['App']['ArchiveDoneItem'](arg1);
}

export function ArchiveTask(arg1) {
  return window['go']['main']['App']['ArchiveTask'](arg1);
}

export function AttachTask(arg1, arg2) {
  return window['go']['main']['App']['AttachTask'](arg1, arg2);
}

export function DetachTask(arg1) {
  return window['go']['main']['App']['DetachTask'](arg1);
}

export function GenerateDebrief(arg1) {
  return window['go']['main']['App']['GenerateDebrief'](arg1);
}

export function GetDemoSnapshot() {
  return window['go']['main']['App']['GetDemoSnapshot']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetShareServer() {
  return window['go']['main']['App']['GetShareServer']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function IgnoreTask(arg1) {
  return window['go']['main']['App']['IgnoreTask'](arg1);
}

export function OpenPane(arg1) {
  return window['go']['main']['App']['OpenPane'](arg1);
}

export function RefreshSummary(arg1) {
  return window['go']['main']['App']['RefreshSummary'](arg1);
}

export function RestoreTask(arg1) {
  return window['go']['main']['App']['RestoreTask'](arg1);
}

export function ReviewDoneItem(arg1) {
  return window['go']['main']['App']['ReviewDoneItem'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartReadonlyServer() {
  return window['go']['main']['App']['StartReadonlyServer']();
}
